### ISSUE TITLE
Translate mockup into database tables

### ISSUE THREAD

**Issue by isjxique** [akhan118/shelter-API#6]
Look over database images on slack and post suggested tables and corresponding fields. You can post them as comments on this thread or add them to the board on the projects tab: https://github.com/akhan118/shelter-API/projects/1

**Comment by MC313** [comment]
We should consider the case that a organization might have 2 users that log into the admin portal to update their availability. Should each user have their own account? Or should both users share a set of credentials?

**Comment by TechnoSayge** [comment]
- No database currently exists?
-Once db is created/built the next step would be to use Gii to create the model?  Where should the model be placed because I see there is a module\v1\controllers directory...are we adding the config directory under module\v1\config? @ish256 @akhan118

**Comment by TechnoSayge** [comment]
Update to my initial questions:

No database currently exists?
-Once db is created/built the next step would be to use Gii to create the model? Where should the model be placed because I see there is a module\v1\controllers directory...are we adding the new model for API under module\v1\controller? @ish256 @akhan118

**Comment by TechnoSayge** [comment]
Disregard the question above related to Issue #6.  I was interchanging the word model and module.

**Comment by isjxique** [comment]
Initial version of database has been pushed out. Pull current build and use yii migrate to get it.
